--- #game of life deploying on qa & dev envs
- hosts: all
  user: service_velocity
  become: yes
  connection: ssh
  gather_facts: yes


  tasks:
    - name: installing git
      action: yum pkg=git state=present 
    
    - name: install docker
      action: yum pkg=docker state=present
      
    - name: docker start
      action: service name=docker state=restarted
      
    - name: copy file
      action: copy src=/home/service_velocity/mnt/project/game-of-life/gameoflife-web/target/gameoflife.war dest=/home/service_velocity

    - name: copy docker-compose
      action: copy src=/home/service_velocity/mnt/project/project/docker-compose.yaml dest=/home/service_velocity
    

